# Generated by Django 4.1.5 on 2023-11-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Usuario')),
                ('Gmail', models.CharField(max_length=50, verbose_name='Gmail')),
                ('Contrasena', models.CharField(max_length=50, verbose_name='Contrasena')),
                ('nombreAlumno', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
