# Generated by Django 4.2.7 on 2023-11-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumno_delete_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Contrasena',
            new_name='password',
        ),
    ]
