# Generated by Django 4.2.7 on 2023-11-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_contrasena_alumno_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombreAlumno',
            new_name='user',
        ),
    ]
