# Generated by Django 4.1.5 on 2023-11-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nombrealumno_alumno_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('idConductor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Usuario')),
                ('Gmail', models.CharField(max_length=50, verbose_name='Gmail')),
                ('password', models.CharField(max_length=50, verbose_name='Contrasena')),
                ('user', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
            ],
        ),
    ]
