# Generated by Django 4.2.7 on 2023-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='idConductor',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Conductor'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Nombre de Conductor'),
        ),
    ]
