# Generated by Django 4.2.7 on 2023-11-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_conductor_idconductor_alter_conductor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='password',
            new_name='contrasena',
        ),
    ]
