# Generated by Django 4.2.7 on 2023-11-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_password_conductor_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='contrasena',
            new_name='password',
        ),
    ]
