# Generated by Django 4.2.7 on 2023-11-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_contrasena_conductor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='autoMarca',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='autoPatente',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Patente'),
        ),
    ]
