# Generated by Django 4.2.7 on 2023-11-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_conductor_automarca_conductor_autopatente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='valorViaje',
            field=models.IntegerField(default=None, null=True, verbose_name='Valor viaje'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='autoMarca',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Marca auto'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='autoPatente',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Patente auto'),
        ),
    ]
