# Generated by Django 4.2.7 on 2023-11-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_conductor_valorviaje_alter_conductor_automarca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='HoraSalida',
            field=models.TimeField(default=None, null=True, verbose_name='Horas Salida'),
        ),
    ]
