# Generated by Django 4.2.7 on 2023-11-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_conductor_horasalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Gmail',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Gmail'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='password',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Contrasena'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Nombre de Usuario'),
        ),
    ]
